env progression

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -56,7 +56,7 @@ jobs:
     steps:
       - name: Setup Snyk CLI
         uses: snyk/actions/setup@main
-        
+
       - name: Checkout repository
         uses: actions/checkout@v4
 
@@ -117,9 +117,40 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: snyk container test ${{ env.IMAGE_REF }} --severity-threshold=high || true
 
-  deploy:
+  deploy-dev:
     needs: build
     runs-on: ubuntu-latest
+    environment: dev
+    steps:
+      - name: Log into GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+  
+      - name: installing jq
+        run: sudo apt-get install jq -y
+  
+      - name: Pull image
+        run: docker pull ${{ needs.build.outputs.image_ref }}
+    
+      - name: Run container (Dev)
+        run: docker run -d --name dev-node-container -p 3000:3000 ${{ needs.build.outputs.image_ref }}
+    
+      - name: Test app
+        run: |
+          sleep 5
+          curl -s http://localhost:3000/health | grep "Still working" && echo "PASS ✅" || echo "FAIL ❌"
+  
+      - name: Check container health status   
+        run: |
+          docker inspect --format='{{json .State.Health}}' dev-node-container | jq
+  
+  deploy-staging:
+    needs: deploy-dev
+    runs-on: ubuntu-latest
+    environment: staging
     steps:
       - name: Log into GHCR
         uses: docker/login-action@v3
@@ -130,11 +161,44 @@ jobs:
   
       - name: Pull image
         run: docker pull ${{ needs.build.outputs.image_ref }}
-  
-      - name: Run container
-        run: docker run -d -p 3000:3000 ${{ needs.build.outputs.image_ref }}
-  
+    
+      - name: Run container (Staging)
+        run: docker run -d --name staging-node-container -p 3001:3000 ${{ needs.build.outputs.image_ref }}
+    
       - name: Test app
         run: |
           sleep 5
-          curl -s http://localhost:3000/health | grep "Still working" && echo "PASS ✅" || echo "FAIL ❌"
+          curl -s http://localhost:3001/health | grep "Still working" && echo "PASS ✅" || echo "FAIL ❌"
+      - name: Check container health status   
+        run: |
+          docker inspect --format='{{json .State.Health}}' staging-node-container | jq
+  
+  deploy-prod:
+    needs: deploy-staging
+    runs-on: ubuntu-latest
+    environment: prod
+    steps:
+      - name: Manual Approval
+        uses: hmarr/auto-approve-action@v2
+        if: github.event_name == 'workflow_dispatch'
+  
+      - name: Log into GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+  
+      - name: Pull image
+        run: docker pull ${{ needs.build.outputs.image_ref }}
+    
+      - name: Run container (Prod)
+        run: docker run -d --name prod-node-container -p 3002:3000 ${{ needs.build.outputs.image_ref }}
+    
+      - name: Test app
+        run: |
+          sleep 5
+          curl -s http://localhost:3002/health | grep "Still working" && echo "PASS ✅" || echo "FAIL ❌"
+      - name: Check container health status   
+        run: |
+          docker inspect --format='{{json .State.Health}}' prod-node-container | jq
